[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 80
target-version = ["py39"]

[tool.isort]
profile = "black"
skip = "migrations"
line_length = 88
known_first_party = ["my_dagster_project"]
